kind: Pod
apiVersion: v1
metadata:
  name: phpfpm
  labels:
    matchLabel: appMy
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: server-config
  containers:
    - image: app-php:1.0.2
      name: app-phpfpm
      ports:
        - containerPort: 9000
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
    - image: nginx:1.7.9
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
