apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  nginx.conf: |
    events {
      }
      http {
        server {
          listen 80 default_server;
          listen [::]:80 default_server;

          # Set nginx to serve files from the shared volume!
          root /var/www/html;
          server_name _;
          location / {
            try_files $uri /index.php$is_args$args;
          }
          location ~ \.php$ {
            fastcgi_pass cluster-ip-php:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            internal;
          }

          error_log /var/log/nginx/project_error.log;
          access_log /var/log/nginx/project_access.log;
        }
      }
